-- MySQL Script generated by MySQL Workbench
-- Mon Apr 24 22:02:13 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema semi_restful_users
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema semi_restful_users
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `semi_restful_users` DEFAULT CHARACTER SET utf8 ;
USE `semi_restful_users` ;

-- -----------------------------------------------------
-- Table `semi_restful_users`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `semi_restful_users`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(200) NULL,
  `last_name` VARCHAR(200) NULL,
  `email` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
