# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170512_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fun',
            field=models.BooleanField(default=True),
        ),
    ]
