# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_fun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fun',
            field=models.BooleanField(default=None),
        ),
    ]
