# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20170512_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fun',
            field=models.BooleanField(default=True),
        ),
    ]
