# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20170512_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='fun',
        ),
    ]
